---
- name: Collect IOS Device Facts
  connection: network_cli
  hosts: routers
  tasks:
    - name: collect facts
      ios_facts:
        gather_subset: all

      register: output

    - name: show output
      debug:
        var: output

...
